# -*- coding: utf-8 -*-
"""DSFSoloProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1eFnDccXr361RO1vZhiVLI1IExjQhkx
"""

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns


#Keep line commented out durring editing for easier workflow
from google.colab import files
uploaded = files.upload()

#set up main frame, add drop.isna later after we get problems sorted out properly

ds = 'vgsales(data_fix).csv'
df = pd.read_csv(ds)
df.drop(df.columns[0], axis=1, inplace=True)


#setting up important frames, first 4 are just column + total sales, sales frames are just dropping all other sales
#genre_platform is how to set up frames where data is needed to be structured for multiple variables

publisher_sales = df.groupby('Publisher')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
genre_sales = df.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
platform_sales = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
year_sales = df.groupby('Year')['Global_Sales'].sum().sort_values(ascending=False).reset_index()
na_sales = df.drop(columns=['EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']).sort_values(by='NA_Sales', ascending=False).reset_index()
eu_sales = df.drop(columns=['NA_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']).sort_values(by='EU_Sales', ascending=False).reset_index()
jp_sales = df.drop(columns=['NA_Sales', 'EU_Sales', 'Other_Sales', 'Global_Sales']).sort_values(by='JP_Sales', ascending=False).reset_index()
other_sales = df.drop(columns=['NA_Sales', 'EU_Sales', 'JP_Sales', 'Global_Sales']).sort_values(by='Other_Sales', ascending=False).reset_index()
genre_platform_sales = df.groupby(['Genre', 'Platform'])['Global_Sales'].sum().reset_index()




display(df)

#Question 1: Which publishers dominate the video game market based on global sales?

#Data Prep
publisher_stats = df.groupby('Publisher').agg({
    'Global_Sales': 'sum',
    'Name': 'count'
}).rename(columns={'Name': 'Game_Count'}).reset_index()

publisher_stats['Avg_Sales'] = publisher_stats['Global_Sales'] / publisher_stats['Game_Count']

#Sort and take top 10
publisher_stats = publisher_stats.sort_values(by='Global_Sales', ascending=False)
top_publishers = publisher_stats.head(10)

#Plotting
plt.figure(figsize=(12,6))

scatter = plt.scatter(
    top_publishers['Game_Count'],
    top_publishers['Global_Sales'],
    s=top_publishers['Avg_Sales'] * 200,   # bigger bubbles
    c=top_publishers['Avg_Sales'],         # color = efficiency
    cmap='viridis',
    alpha=0.7
)

#Add colorbar
plt.colorbar(scatter, label='Average Sales per Game')

#Label each point
for i, row in top_publishers.iterrows():
    plt.text(
        row['Game_Count'] + 5,
        row['Global_Sales'] + 5,
        row['Publisher'],
        fontsize=9
    )


# Labelling axis
plt.xlabel('Number of Games Released')
plt.ylabel('Total Global Sales (Millions)')
plt.title('Top Publishers: Output vs Total Sales (Size & Color = Avg Sales per Game)')
plt.grid(True)

plt.tight_layout()
plt.show()

# Question 2: How has the number of game releases changed over time and what genres are more prevalent in those years?

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

#Clean and Filter Data
year_genre = df[['Year', 'Genre']].dropna()
year_genre['Year'] = year_genre['Year'].astype(int)

#Cut off after 2015
year_genre = year_genre[year_genre['Year'] <= 2015]

#Count releases
year_genre_counts = year_genre.groupby(['Year', 'Genre']).size().reset_index(name='Count')

#Pivot
genre_pivot = year_genre_counts.pivot(index='Year', columns='Genre', values='Count').fillna(0)
#Had to figure out how to use multiple colors using AI here
#Custom Colors
colors = plt.cm.tab20.colors  # 20 distinct colors

# Plot
genre_pivot.plot(
    kind='area',
    figsize=(14, 7),
    stacked=True,
    color=colors
)

plt.xlabel("Year")
plt.ylabel("Number of Game Releases")
plt.title("Video Game Releases by Genre Over Time (Up to 2015)")
plt.legend(title="Genre", bbox_to_anchor=(1.2, 1), loc='upper left')
plt.grid(True)
plt.show()


# Filter early years
early_data = genre_pivot[genre_pivot.index <= 1995]

# Plot
early_data.plot(
    kind='area',
    figsize=(14, 7),
    stacked=True,
    color=colors
)

plt.xlabel("Year")
plt.ylabel("Number of Game Releases")
plt.title("Video Game Releases by Genre (Early Years: Pre-1995)")
plt.legend(title="Genre", bbox_to_anchor=(1.2, 1), loc='upper left')
plt.grid(True)
plt.show()
# ML:Polynomial regression on total yearly releases

# Count total game releases per year
games_per_year = year_genre.groupby('Year').size().reset_index(name='Game_Count')

# Set up X and y
X = games_per_year[['Year']]
y = games_per_year['Game_Count']

# Polynomial features
poly = PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(X)

# Train model
model = LinearRegression()
model.fit(X_poly, y)

# Predict
y_pred = model.predict(X_poly)

# R^2 score
r2 = r2_score(y, y_pred)

# Plot actual vs polynomial trend
plt.figure(figsize=(12, 6))
plt.scatter(games_per_year['Year'], games_per_year['Game_Count'], label='Actual Releases')
plt.plot(games_per_year['Year'], y_pred, linewidth=3, label=f'Polynomial Regression (R² = {r2:.3f})')

plt.xlabel("Year")
plt.ylabel("Number of Game Releases")
plt.title("Polynomial Trend of Total Game Releases Over Time")
plt.legend()
plt.grid(True)
plt.show()